### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by glimchb**
Add readline dependency to the readme file

### CODE REVIEW

**Comment by mraineri** [comment]
@pboyd04 , CMakeLists.txt does not list readline as required, but rpm/libredfish.spec does have it marked as required. Which one is correct?

**Comment by pboyd04** [comment]
Readline is used by the CLI example code only. It isn't needed to build the library just one of the tools.

**Comment by pboyd04** [comment]
In other words, both the CMakeLists.txt and the spec file are correct. We don't require it to build, but the build we have for the CLI tool requires that it is installed. It should not be added to the readme as it isn't required to build the library.

**Comment by mraineri** [comment]
5/2: Closing; since the library itself does not require readline, a user can download the source code and build it themselves without having readline installed. The issue is only when installing via rpm, but systems that do that will almost certainly have it preinstalled.

**Comment by glimchb** [comment]
@mraineri I opened this PR cause I was trying to install libredfish via RPM and readline wasn't not there... Anyhow your call...

**Pull request closed without merging**
